var a = 10;
document.write("Result :");
document.write("<br>The Value of a is :"+a);
document.write("<br>******************");
document.write("<br>The Value of ++a is :"+ ++a);
document.write("<br>The Value of a is :"+ a);
document.write("<br>******************");
document.write("<br>The Value of a++ is :"+ a++ );
document.write("<br>The Value of a is :"+ a);
document.write("<br>******************");
document.write("<br>The Value of --a is :"+ --a );
document.write("<br>The Value of a is :"+ a);
document.write("<br>******************");
document.write("<br>The Value of a++ is :"+ a-- );
document.write("<br>The Value of a is :"+ a);
document.write("<br>******************");
