var a;
document.write("<h1>");
document.write("Value after variable declaration is " + a);
a = 5;
document.write("<br> Initial Value : " + a);
a += 1;
document.write("<br>Value after increment is : " + a);
a = a + 7;
document.write("<br>Value After Addition is : " + a);
a -= 1;
document.write("<br>Value after decrement is : " + a);
a = a % 3;
document.write("<br>The remainder is : " + a) ;